
services:
  - type: web
    name: lyricbeats-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production

  - type: web
    name: lyricbeats-frontend
    env: node
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    staticPublishPath: build
    autoDeploy: true
